#!/usr/bin/env python3
"""Interactively create a small release report."""

from pathlib import Path


def _read(prompt: str) -> str:
    print(prompt, end="", flush=True)
    return input().strip()


def main() -> None:
    release_name = _read("Release name: ")
    mode = _read("Report mode (1=compact, 2=detailed): ")
    if not release_name:
        raise ValueError("release name is required")
    if mode not in {"1", "2"}:
        raise ValueError("report mode must be 1 or 2")

    lines = [
        f"Release: {release_name}",
        f"Mode: {'detailed' if mode == '2' else 'compact'}",
        "Generated by: skill_exec",
    ]
    if mode == "2":
        lines.extend([
            "Checks:",
            "- interactive stdin received",
            "- output file generated",
            "- artifact collection requested",
        ])

    output = Path("out/report.txt")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Created {output}")


if __name__ == "__main__":
    main()
