# Tencent is pleased to support the open source community by making tRPC-Agent-Python available.
#
# Copyright (C) 2026 Tencent. All rights reserved.
#
# tRPC-Agent-Python is licensed under Apache-2.0.
"""
Streaming Function Tool Implementation.

This module implements the StreamingFunctionTool class which extends the standard
FunctionTool to support streaming function call arguments. This enables real-time
streaming of tool arguments as they are generated by the LLM.

Key Features:
- Extends FunctionTool with streaming argument support
- Automatically detected during process_llm_request to enable streaming
- Streaming events are yielded through Runner for unified event handling
- Compatible with standard tool execution pipeline
- Works with ToolSet - streaming tools inside ToolSet are properly detected

Usage:
    Create StreamingFunctionTool directly from various sources:

        from trpc_agent_sdk.tools import StreamingFunctionTool, FunctionTool

        # From a sync function
        tool = StreamingFunctionTool(write_file)

        # From an async function
        tool = StreamingFunctionTool(async_write_file)

        # From an existing FunctionTool
        tool = StreamingFunctionTool(FunctionTool(write_file))

Example Usage:
    from trpc_agent_sdk.tools import StreamingFunctionTool
    from trpc_agent_sdk.models import TOOL_STREAMING_ARGS

    def write_file(path: str, content: str) -> dict:
        '''Write content to a file.'''
        with open(path, "w") as f:
            f.write(content)
        return {"success": True}

    streaming_tool = StreamingFunctionTool(write_file)

    # Use with LlmAgent - streaming is auto-detected at runtime
    agent = LlmAgent(
        name="writer",
        tools=[streaming_tool],
    )

    # Consume streaming events through Runner
    async for event in runner.run_async(...):
        if event.is_streaming_tool_call():
            for part in event.content.parts:
                if part.function_call:
                    delta = part.function_call.args.get(TOOL_STREAMING_ARGS, "")
                    print(f"Streaming: {delta}")
"""

from typing import Any
from typing import Callable
from typing import Optional
from typing import Union
from typing_extensions import override

from trpc_agent_sdk.filter import BaseFilter

from ._function_tool import FunctionTool


class StreamingFunctionTool(FunctionTool):
    """A tool that supports streaming function call arguments.

    This class extends FunctionTool to indicate that this tool should receive
    streaming argument updates. When used with LlmAgent, the framework will
    automatically enable streaming for tools of this type.

    The is_streaming property returns True, which is detected during
    ToolsProcessor.process_llm_request() to dynamically determine which tools
    should receive streaming arguments. This works even when the tool is
    inside a ToolSet.

    Streaming events are yielded through Runner.run_async() and can be consumed
    using event.is_streaming_tool_call() to detect streaming tool call events.

    The streaming delta content is available in:
        part.function_call.args.get("tool_streaming_args", "")

    Attributes:
        func: The function to wrap

    Example:
        # Create streaming tool directly from function
        tool = StreamingFunctionTool(write_file)

        # Or from existing FunctionTool
        tool = StreamingFunctionTool(FunctionTool(write_file))

        # Consume streaming events
        async for event in runner.run_async(...):
            if event.is_streaming_tool_call():
                for part in event.content.parts:
                    if part.function_call:
                        delta = part.function_call.args.get("tool_streaming_args", "")
                        print(f"Received: {delta}")
    """

    def __init__(
        self,
        func: Union[Callable[..., Any], FunctionTool],
        filters_name: Optional[list[str]] = None,
        filters: Optional[list[BaseFilter]] = None,
    ):
        """Initialize StreamingFunctionTool.

        Args:
            func: The function to wrap. Can be:
                - A sync function (def write_file)
                - An async function (async def write_file)
                - A callable object (class with __call__)
                - An existing FunctionTool instance
            filters_name: Optional list of filter names to apply
            filters: Optional list of filter instances to apply
        """
        # If func is already a FunctionTool, extract its underlying function
        if isinstance(func, FunctionTool):
            # Copy filters from the original FunctionTool if not explicitly provided
            if filters_name is None and filters is None:
                filters = func.filters.copy() if func.filters else None
            func = func.func

        super().__init__(func=func, filters_name=filters_name, filters=filters)

    @property
    @override
    def is_streaming(self) -> bool:
        """Return True to indicate this tool supports streaming arguments.

        This property is checked during ToolsProcessor.process_llm_request()
        to dynamically determine which tools should receive streaming arguments.

        Returns:
            bool: Always True for StreamingFunctionTool.
        """
        return True
