# Generated Graph Workflow: `{{ workflow_name }}`

This project is generated by `python -m trpc_agent_dsl.codegen`.

## Layout
- `agent/`: graph workflow implementation (`agent.py`, `state.py`, `nodes.py`, etc.)
- `.env`: generated environment variables for local runs
- `run_agent.py`: local interactive runner for quick functional checks
{% if has_service %}
- `trpc_main.py`: tRPC server entrypoint
- `trpc_python.yaml`: tRPC server config
- `client.py`: service-side client test script
{% endif %}
- `requirements.txt`: runtime dependencies
{% if has_service %}
{% if service_mode == "http" %}
- `_agent_runner.py`, `http_service.py`: HTTP/SSE service glue
{% elif service_mode == "a2a" %}
- `a2a_service.py`: A2A service registration
- `trpc_python_client.yaml`: tRPC client config for A2A test client
{% else %}
- `agui_service.py`: AG-UI service registration
{% endif %}
{% endif %}

## Service Mode
{% if has_service %}
- `{{ service_mode }}`
{% else %}
- `none`
{% endif %}
{% for note in service_notes %}
- {{ note }}
{% endfor %}

## Required Environment Variables
{% if env_hints %}
{% for name in env_hints %}
- `{{ name }}`
{% endfor %}
{% else %}
- None
{% endif %}

## Setup Environment
```bash
python3.12 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python run_agent.py
```

## Run Local Agent Quickly
```bash
python run_agent.py
```

{% if has_service %}
## Run tRPC Service
```bash
python trpc_main.py
```

## Client Test
{% for step in client_steps %}
```bash
{{ step }}
```
{% endfor %}
{% endif %}
