# Tencent is pleased to support the open source community by making tRPC-Agent-Python available.
#
# Copyright (C) 2026 Tencent. All rights reserved.
#
# tRPC-Agent-Python is licensed under Apache-2.0.
"""Example of a CodeAct generation method."""

from pathlib import Path
from typing import Literal

from pydantic import BaseModel

from trpc_agent_sdk.agents import LlmAgent
from trpc_agent_sdk.codeact import (
    CodeActImplementationPolicy,
    FileCodeActImplementationStore,
)
from trpc_agent_sdk.models import OpenAIModel
from trpc_agent_sdk.tools import CodeActTool

from .config import get_model_config


class OrderRecord(BaseModel):
    """One order included in the operations analysis."""

    order_id: str
    customer_id: str
    amount: float
    status: Literal["paid", "shipped", "delivered", "cancelled"]
    days_since_update: int


class OrderOperationsReport(BaseModel):
    """Structured operations report generated by the incomplete function."""

    status_counts: dict[str, int]
    active_amount: float
    overdue_order_ids: list[str]
    high_value_customer_ids: list[str]


def analyze_order_operations(
    orders: list[OrderRecord],
    overdue_days: int = 3,
    high_value_threshold: float = 1500.0,
) -> OrderOperationsReport:
    """Analyze order operations using deterministic business rules.

    Count every order by status. Exclude cancelled orders from active_amount
    and customer spending. An order is overdue when its status is paid or
    shipped and days_since_update is at least overdue_days. A customer is high
    value when their non-cancelled order total is at least
    high_value_threshold. Sort both returned ID lists.
    """
    ...  # noqa: PIE790  # CodeActTool implementation marker


def create_agent(
    code_act_dir: Path,
    implementation_policy: CodeActImplementationPolicy | str,
) -> LlmAgent:
    """Create an Agent that can invoke an LLM-implemented function tool."""
    api_key, base_url, model_name = get_model_config()
    model = OpenAIModel(
        model_name=model_name,
        api_key=api_key,
        base_url=base_url,
    )
    implementation_store = FileCodeActImplementationStore(code_act_dir)
    return LlmAgent(
        name="code_act_function_demo",
        model=model,
        instruction=(
            "Use analyze_order_operations whenever the user asks to analyze "
            "order operations. Pass every supplied order without omission."
        ),
        tools=[
            CodeActTool(
                analyze_order_operations,
                implementation_store=implementation_store,
                implementation_policy=implementation_policy,
            )
        ],
    )
