"""Named limits and defaults used by the code review example."""

from pathlib import Path

APP_NAME = "skills_code_review_agent"
DEFAULT_DB_URL = "sqlite:///skills_code_review.db"
DEFAULT_OUTPUT_DIR = Path("reports")
DEFAULT_CONTEXT_LINES = 3

MAX_DIFF_BYTES = 2 * 1024 * 1024
MAX_FILE_BYTES = 512 * 1024
MAX_FILES = 200
MAX_HUNKS_PER_FILE = 500
MAX_CHANGED_LINES = 20_000
MAX_PATH_LENGTH = 512
MAX_OUTPUT_BYTES = 64 * 1024
MAX_JSONL_LINES = 2_000
MAX_JSONL_LINE_BYTES = 16 * 1024
MAX_JSON_DEPTH = 12
MAX_TEXT_FIELD_LENGTH = 8_192

GIT_TIMEOUT_SECONDS = 15.0
FILTER_TIMEOUT_SECONDS = 5.0
SANDBOX_TIMEOUT_SECONDS = 30.0
CLEANUP_TIMEOUT_SECONDS = 5.0
MODEL_TIMEOUT_SECONDS = 45.0
REPORT_TIMEOUT_SECONDS = 5.0
TOTAL_TIMEOUT_SECONDS = 90.0

MIN_ACTIONABLE_CONFIDENCE = 0.70
MAX_RETRY_ATTEMPTS = 2
SQLITE_BUSY_TIMEOUT_MILLISECONDS = 5_000
DB_ID_LENGTH = 64
DB_STATUS_LENGTH = 32
DB_CATEGORY_LENGTH = 64
DB_PATH_LENGTH = 512
DB_TITLE_LENGTH = 512
DB_SOURCE_LENGTH = 256

ALLOWED_ENV_NAMES = frozenset({
    "LANG",
    "LC_ALL",
    "PYTHONIOENCODING",
    "PYTHONUTF8",
})
ALLOWED_INTERPRETERS = frozenset({"python", "python3"})
BLOCKED_PATH_PARTS = frozenset({
    ".git",
    ".ssh",
    ".aws",
    ".config",
    "etc",
    "proc",
    "sys",
})

REDACTION_MARKER = "[REDACTED]"
LOCAL_RUNTIME_OPT_IN_ENV = "TRPC_CODE_REVIEW_ALLOW_UNSAFE_LOCAL"
CONTAINER_TEST_ENV = "TRPC_CODE_REVIEW_CONTAINER_TEST"
DB_URL_ENV = "TRPC_CODE_REVIEW_DB_URL"
ASYNC_SQL_DRIVER_MARKERS = (
    "+aiosqlite",
    "+asyncpg",
    "+aiomysql",
)
