# -*- coding: utf-8 -*-
#
# Copyright @ 2026 Tencent.com
"""Chain Agent Implementation.

This module provides the ChainAgent class which executes sub-agents sequentially,
one after another. This is useful for creating workflows where agents need to
process results from previous agents in order.

Classes:
    ChainAgent: A shell agent that runs its sub-agents in sequence
"""

from __future__ import annotations

from typing import AsyncGenerator
from typing_extensions import override

from trpc_agent_sdk.context import InvocationContext
from trpc_agent_sdk.events import Event

from ._base_agent import BaseAgent


class ChainAgent(BaseAgent):
    """A shell agent that runs its sub-agents in sequence.

    The ChainAgent executes each sub-agent one after another, allowing
    subsequent agents to process and build upon the outputs of previous agents.
    This is ideal for creating sequential workflows where the order of execution
    matters.

    Example:
        ```python
        chain_agent = ChainAgent(
            name="data_processing_chain",
            description="Process data through multiple steps",
            sub_agents=[
                data_collection_agent,
                data_validation_agent,
                data_analysis_agent,
                report_generation_agent
            ]
        )
        ```
    """

    @override
    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        """Execute sub-agents sequentially.

        Args:
            ctx: The invocation context for this agent

        Yields:
            Event: Events generated by each sub-agent in sequence
        """
        for sub_agent in self.sub_agents:
            async for event in sub_agent.run_async(ctx):
                yield event
