# -*- coding: utf-8 -*-
#
# Copyright @ 2026 Tencent.com
"""Cycle Agent Implementation.

This module provides the CycleAgent class which executes sub-agents in a loop
until escalation or max_iterations, similar to ADK's LoopAgent.

Classes:
    CycleAgent: A shell agent that runs its sub-agents in a cycle/loop
"""

from __future__ import annotations

from typing import AsyncGenerator
from typing import Optional
from typing_extensions import override

from trpc_agent_sdk.context import InvocationContext
from trpc_agent_sdk.events import Event

from ._base_agent import BaseAgent


class CycleAgent(BaseAgent):
    """A shell agent that runs its sub-agents in a loop.

    When a sub-agent generates an event with escalate flag set or max_iterations
    are reached, the cycle agent will stop.

    This is useful for:
    - Iterative refinement processes
    - Continuous monitoring and adjustment
    - Multi-round negotiation or problem-solving

    Example:
        ```python
        cycle_agent = CycleAgent(
            name="iterative_solver",
            description="Iteratively solve problems until convergence",
            max_iterations=5,
            sub_agents=[
                analysis_agent,
                solution_agent,
                validation_agent
            ]
        )
        ```
    """

    max_iterations: Optional[int] = None
    """The maximum number of iterations to run the cycle agent.

    If not set, the cycle agent will run indefinitely until a sub-agent
    escalates.
    """

    @override
    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        """Execute sub-agents in a loop until escalation or max iterations.

        Args:
            ctx: The invocation context for this agent

        Yields:
            Event: Events generated by sub-agents in each iteration
        """
        times_looped = 0
        while not self.max_iterations or times_looped < self.max_iterations:
            for sub_agent in self.sub_agents:
                async for event in sub_agent.run_async(ctx):
                    yield event
                    if ctx.actions.escalate:
                        return
            times_looped += 1
        return
