# Tencent is pleased to support the open source community by making tRPC-Agent-Python available.
#
# Copyright (C) 2026 Tencent. All rights reserved.
#
# tRPC-Agent-Python is licensed under Apache-2.0.
"""Allowed difference definitions for cross-backend comparison.

These define which field-level differences are expected and acceptable
between different backends, along with their justifications.
"""

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field
from typing import Any


@dataclass
class AllowedDiff:
    """Definition of an allowed field-level difference between backends.

    Attributes:
        field_path_pattern: Glob-like pattern for the field path.
            Examples: "*.timestamp", "events[*].id", "summary.summary_timestamp"
        allowed: Whether this diff is allowed.
        reason: Explanation of why this diff is allowed.
    """

    field_path_pattern: str
    allowed: bool = True
    reason: str = ""


ALLOWED_DIFFS: list[AllowedDiff] = [
    AllowedDiff(
        field_path_pattern="*.timestamp",
        allowed=True,
        reason="Timestamp precision varies by backend (float vs DB vs Redis serialization)",
    ),
    AllowedDiff(
        field_path_pattern="*.id",
        allowed=True,
        reason="Event IDs are auto-generated by each backend independently",
    ),
    AllowedDiff(
        field_path_pattern="*.invocation_id",
        allowed=True,
        reason="Invocation IDs are auto-generated by each backend",
    ),
    AllowedDiff(
        field_path_pattern="*.request_id",
        allowed=True,
        reason="Request IDs may differ between backends",
    ),
    AllowedDiff(
        field_path_pattern="*.last_update_time",
        allowed=True,
        reason="Last update time varies due to backend write latency differences",
    ),
    AllowedDiff(
        field_path_pattern="*.save_key",
        allowed=True,
        reason="save_key is an internal computed field; formatting may differ",
    ),
    AllowedDiff(
        field_path_pattern="*.summary_timestamp",
        allowed=True,
        reason="Summary generation timestamp varies by backend",
    ),
    AllowedDiff(
        field_path_pattern="*.metadata",
        allowed=True,
        reason="Metadata may include backend-specific fields",
    ),
    AllowedDiff(
        field_path_pattern="*.parent_invocation_id",
        allowed=True,
        reason="Parent invocation ID generation differs between backends",
    ),
    AllowedDiff(
        field_path_pattern="*.filter_key",
        allowed=True,
        reason="Filter key may be computed differently across backends",
    ),
    AllowedDiff(
        field_path_pattern="*.branch",
        allowed=True,
        reason="Branch may be set differently across backends",
    ),
    AllowedDiff(
        field_path_pattern="*.model_flags",
        allowed=True,
        reason="Model flags are internal and may differ in representation",
    ),
    AllowedDiff(
        field_path_pattern="*.version",
        allowed=True,
        reason="Version field may differ in default value representation",
    ),
    AllowedDiff(
        field_path_pattern="*.object",
        allowed=True,
        reason="Object type field is backend-specific metadata",
    ),
    AllowedDiff(
        field_path_pattern="*.tag",
        allowed=True,
        reason="Tag is optional business metadata; may be handled differently",
    ),
    AllowedDiff(
        field_path_pattern="*.visible",
        allowed=True,
        reason="Visible flag may be serialized differently",
    ),
    AllowedDiff(
        field_path_pattern="*.requires_completion",
        allowed=True,
        reason="Requires completion may differ in default value handling",
    ),
    AllowedDiff(
        field_path_pattern="*.conversation_count",
        allowed=True,
        reason="Conversation count may be tracked differently",
    ),
    AllowedDiff(
        field_path_pattern="*.long_running_tool_ids",
        allowed=True,
        reason="Long running tool IDs are backend-specific internal state",
    ),
]


def is_allowed_diff(field_path: str) -> tuple[bool, str]:
    """Check if a field path difference is allowed.

    Args:
        field_path: Dot-separated field path, e.g. "events[0].timestamp"

    Returns:
        Tuple of (is_allowed, reason).
    """
    import fnmatch
    for ad in ALLOWED_DIFFS:
        if fnmatch.fnmatch(field_path, ad.field_path_pattern):
            return ad.allowed, ad.reason
    return False, ""